title: Kim Larson # your name (or website title) here
logo: "/images/KimEmmy.jpeg?raw=true" # your photo (or logo) here
description: >
  <B>Survey Geek, Neighborhood Nerd</b><br><br>
  I'm a community advocate and survey enthusiast with a background in market research and economic development.
  I'm currently VP of Insights at Luminoso, an AI text analytics company founded out of MIT. 
  I love turning challenges into opportunities, building strong, trust-based relationships through collaboration, and thrive in creative, hands-on environments.
  <br><br>
  My ongoing passion projects include the Portland Neighborhood Culture Study Series, a self-started initative rooted in community insight and professional growth.
  I'm always open to connecting and exploring ways to contribute meaningfully to mission-driven teams.<br><br><br>

  <b>How to contact me</b><BR>
  <a href="https://www.linkedin.com/in/kimalarson/">LinkedIn</a> <br>
  <a href="mailto:klarson@luminoso.com?subject=Github%20Connection&body=Hey%20Kim,%20I'm%20interested%20in%20what%20you%20do!">Email: KLarson@Luminoso.com</a>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

