title: Kim Larson # your name (or website title) here
logo: "/images/KimEmmy.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Survey Geek, Neighborhood Nerd
  <br><br>
  I'm a community advocate and survey enthusiast with a background in market research and economic development. 
  I love turning challenges into opportunities and building strong, trust-based relationships through collaboration.

I thrive in creative, hands-on environments. 
Ongoing projects include the Portland Neighborhood Culture Study Series reflect my passion for community insight and professional growth. 
I'm always open to connecting and exploring ways to contribute meaningfully to mission-driven teams.
<br><br>
  <a href="https://www.linkedin.com/in/kimalarson/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

