title: Kim Larson # your name (or website title) here
logo: "/images/1000028032.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Survey Geek, Neighborhood Nerd
  <br><br>
  I am a passionate community advocate and survey geek with extensive experience in market research and economic development. 
  My professional journey has equipped me with the skills to explore objectives and collaborate with teams to develop effective solutions. 
  I find immense satisfaction in transforming challenging situations into positive outcomes and building lasting relationships based on earned trust as we collaborate to solve problems.
  <br><br>
  I thrive in environments that value innovative thinking, and experiential learning. 
  My recent projects, including the St. Johns Neighborhood Association 2024 Culture Study and Luminoso's ongoing Market Research webinar series, highlight my ability to assess community strengths and foster professional development. 
  I am excited about opportunities to contribute to dynamic and supportive environments and am always open to connecting and discussing how I can add value to your team.
  <br><br>
  <a href="https://www.linkedin.com/in/kimalarson/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins: jekyll-remote-theme
